project: nyc_taxi
registry: data/feast/registry.db
provider: local

offline_store:
  type: file

online_store:
  type: redis
  connection_string: "redis://redis:6379/0"

entity_key_serialization_version: 2
